//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BecomeAChef.EF
{
    using BecomeAChef.Utils;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Windows.Media.Imaging;

    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.User1 = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Title { get; set; }
        public string Contents { get; set; }
        public short CookingTimeMinutes { get; set; }
        public byte Portions { get; set; }
        public byte[] Image { get; set; }
        public System.DateTime PublishedTimestamp { get; set; }

        public BitmapImage ImageToUI { 
         
            get 
            {
                return new ImageConverter().LoadImage(Image);
            } 
        }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User1 { get; set; }

       

    }
}
